[book]
authors = ["The Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Programming Multiple Robots with ROS 2"

[build]
create-missing = false

[output.html]
# default-theme = "coal"

[output.latex]
latex = true
pdf = true
markdown = true

#[output.epub]
